### ISSUE TITLE
E-EGOD-11: execution failed with SQL error code '00000' and message 'getDouble: JSON value is not a double

### ISSUE THREAD

**Issue by cyrixsimon** [exasol/exasol-driver-go#108]
Hallo,

if you try to insert a decimal value with a prepared statement you will get an JSON error.

**Error:**
panic: E-EGOD-11: execution failed with SQL error code '00000' and message 'getDouble: JSON value is not a double

**Table structure:**
`create or replace table work.dummy (a integer, b float);`

**Go Code:**
`	
	exadb, err := sql.Open("exasol", config.String())
	if err != nil {
		panic(err)
	}
	defer exadb.Close()

	stmt, err := exadb.Prepare("insert into work.dummy values(?,?)")
	if err != nil {
		panic(err)
	}

	_, err = stmt.Exec(1, 1)
	if err != nil {
		panic(err)
	}
`

**Comment by kaklakariada** [comment]
This is fixed in https://github.com/exasol/exasol-driver-go/releases/tag/v1.0.8
