### ISSUE TITLE
Websocket error: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by cyrixsimon** [exasol/exasol-driver-go#110]
Hello,

when I query a large dataset with a select, I get a websocket error. 

**#Rows**: 350000000
**#Column**s: 39

**Query**
`
select col1, col2 ... from schema.table
`

**Error**
`websocket error: close 1006 (abnormal closure): unexpected EOF`

**Comment by kaklakariada** [comment]
Thank you very much for your bug report! I will ask our product manager to put this and #111 onto the roadmap.

**Comment by kaklakariada** [comment]
@cyrixsimon I am trying to reproduce this error. At what point in time do you get this error? in `database.Query()` or `rows.Scan()`, i.e. did you already receive data when the error occurred?

In my experiment the driver logs the following while running `database.Query()`:
```
[exasol] 2024/06/25 09:43:11 websocket.go:125: W-EGOD-17: could not receive data: 'websocket: close 1006 (abnormal closure): unexpected EOF'
[exasol] 2024/06/25 09:43:11 websocket.go:125: W-EGOD-17: could not receive data: 'websocket: close 1006 (abnormal closure): unexpected EOF'
```
Did you get the same output or a different one?

**Comment by cyrixsimon** [comment]
My analyses have shown that the session is being killed by the database. This case can therefore be cloded, it is an issue on the database. Thanks!

**Comment by kaklakariada** [comment]
@cyrixsimon thanks for your reply, great you could solve the issue!
