### ISSUE TITLE
Rows.Err is not set correctly in the event of an error

### ISSUE THREAD

**Issue by cyrixsimon** [exasol/exasol-driver-go#111]
Hi,

the following error during fetching the data set from the database is not set correctly. 

**Error**
`W-EGOD-17: could not receive data: 'websocket: close 1006 (abnormal closure): unexpected EOF'`

**Code**
`
for rows.Next() {
    err = scanFunc(rows)
    if err != nil {
       return err
    }
}
if err = rows.Err(); err != nil {
    return err
}
`

Rows.Err returns the error for advancing to the next row or error. But the error W-EGOD-17 ... is not set in rows.Err. 

You only see the output of the internal logger of the driver.
`websocket.go:124: W-EGOD-17: could not receive data: 'websocket: close 1006 (abnormal closure): unexpected EOF'`

**Comment by kaklakariada** [comment]
This is fixed with https://github.com/exasol/exasol-driver-go/pull/114
