### ISSUE TITLE
Inappropriate process fetch command

### ISSUE THREAD

**Issue by Darlez** [exasol/exasol-driver-go#26]
I am trying to get big query response and encounter problem: if results doesn't fit in one fetch I get `panic: runtime error: index out of range [18725] with length 18725` (number depends on fetchsize property)
```
goroutine 1 [running]:
github.com/exasol/exasol-driver-go.(*queryResults).Next(0xc000030200, 0xc0002d0320, 0xa, 0xa, 0x1866da0, 0x197eb01)
       ./mod/github.com/exasol/exasol-driver-go@v0.0.0-20210713141110-54f0a9140b6c/result_set.go:106 +0x4a5
```
After some research I discovered the root of issue, I guess. In ./result_set.go in `func (results *queryResults) Next(dest []driver.Value)` there is code

```go
result := &SQLQueryResponseResultSetData{}
err := results.con.send(context.Background(), &FetchCommand{
	Command:         Command{"fetch"},
	ResultSetHandle: results.data.ResultSetHandle,
	StartPosition:   results.rowPointer,
	NumBytes:        results.con.config.FetchSize,
}, result)
if err != nil {
	return err
}

results.fetchedRows = results.fetchedRows + result.NumRowsInMessage
```

But, according [fetch command structure](http://biggis-project.eu/biggis-docs/architecture/exasol-database/exasol-websockets/#fetch-retrieves-data-from-a-result-set), response doesn't have `NumRowsInMessage` field, and thereby application panic, if result set doesn't fit in on fetch.
I suppose, we need change `result.NumRowsInMessage` -> `result.NumRows` and that's all, but I am not so good in low-level driver implementation, so please, check it by yourself and correct me, if I am wrong.

**Comment by Nightapes** [comment]
@Darlez Thank you for reporting the bug and the solution.
We created a fix and release a new version soon.
