### ISSUE TITLE
DSN parsing not working when parameters end with special character

### ISSUE THREAD

**Issue by clementlefevre** [exasol/exasol-driver-go#32]
Following the issue  #23 , i finally found out what the root cause was.

If the password given ends with an exclamation mark, e.g. *user=ARCHIMEDES;password=123Eureka!;encryption=1;usetls=0*, when building the connection configuration in **dsn.go** , the parsed password returned is *123Eureka!;encryption=1* instead of *123Eureka!* 

I could fix the problem by adjusting the following function as follow:
```go
func extractParameters(parametersString string) []string {
        // Original code
	//reg := regexp.MustCompile(`[\w];`)
	//return splitAfter(parametersString, reg)

        // dirty fix
	return strings.Split(parametersString, ";")
}
```

is there a better way to address this issue ?

Thanks a lot in advance,

Best Regards,

Clement.

**Comment by AnastasiiaSergienko** [comment]
Closed with #33
