### ISSUE TITLE
Make parseDsn public

### ISSUE THREAD

**Issue by abergmeier** [exasol/exasol-driver-go#47]
Currently there seems no public way of converting a string DSN to a `DSNConfig`. Would be really helpful if `parseDsn` would be public.

**Comment by Nightapes** [comment]
Hey @abergmeier, thanks for the input. 

With the next release the `parseDsn` function is public.

**Comment by redcatbear** [comment]
Switching ticket type to "feature". @Nightapes, please close with the next release.

**Comment by kaklakariada** [comment]
This was implemented in https://github.com/exasol/exasol-driver-go/pull/49 and released in [v0.3.0](https://github.com/exasol/exasol-driver-go/releases/tag/v0.3.0).
