### ISSUE TITLE
Implement exists logic

### ISSUE THREAD

**Issue by abergmeier** [exasol/exasol-driver-go#48]
Especially for testing it is very beneficial to just ensure that a database object is present.
Currently the error I get is e.g. 
> E-GOD-11: execution failed with SQL error code '42500' and message 'schema RESOURCES_VIEW_TEST_TESTMAIN already exists (Session: 1719069525976612864)'

In these cases it would be good if I could distinct the error cause and say something like:

```golang
if errors.Is(err, exasol.ErrObjectExist) {
  // EOK
}
```

**Comment by redcatbear** [comment]
Shelved, because not in roadmap focus.
