### ISSUE TITLE
toDSN function missing config.schema conversion

### ISSUE THREAD

**Issue by peterkioko** [exasol/exasol-driver-go#56]
Hi,

The toDSN function is missing 'schema' in the list of configs it converts to DSN.
https://github.com/exasol/exasol-driver-go/blob/f7e993fa5682f1eff5373e69913f1c298b89410e/dsn.go#L97
So if you specify a schema via NewConfig it doesn't get passed along to Exasol at connection time.

Regards,
Peter

**Comment by kaklakariada** [comment]
Hi @peterkioko!
Thank you for reporting this! I created #57 to fix this and I will release version 0.3.2 later today.

**Comment by kaklakariada** [comment]
We just release version [v0.3.2](https://github.com/exasol/exasol-driver-go/releases/tag/v0.3.2) including the bugfix.
