### ISSUE TITLE
clientOsUserName is not passed

### ISSUE THREAD

**Issue by sarg** [exasol/exasol-driver-go#58]
When I connect to exasol via the go driver I can see that os_user is empty in `select * from exa_user_sessions;`

**Comment by kaklakariada** [comment]
Hi @sarg,
thank you very much for your ticket and the pull request!
In order to speedup things I created a separate PR #62 with your fix, additional integration tests and changelog.

**Comment by kaklakariada** [comment]
Hi @sarg,
I just release [v0.3.3](https://github.com/exasol/exasol-driver-go/releases/tag/v0.3.3) including this bugfix.
Thanks again for your help!
