### ISSUE TITLE
Import hangs for large files

### ISSUE THREAD

**Issue by cyrixsimon** [exasol/exasol-driver-go#65]
The import command hangs for CSV files with several thousand rows (>10000). Smaller files work properly.

**Comment by kaklakariada** [comment]
Hi @cyrixsimon ,
we just released [v0.4.2](https://github.com/exasol/exasol-driver-go/releases/tag/v0.4.2) with PR #65 as bugfix. Thanks to @Nightapes for finding the root cause and fixing it!
