### ISSUE TITLE
Exasol behind a proxy

### ISSUE THREAD

**Issue by elferherrera** [exasol/exasol-driver-go#69]
Thanks a lot for your work on this driver. It seems to be what I'm looking for. My question is if it is possible to use the proxy object to put exasol behind it?

We want to do this to add extra security to the connections and to sniff the queries that are sent to exasol before they reach the dB. My idea is to use a TCP listener and then decode the information to send it to the DB. 

Do you think it is possible to do it with this repo?

**Comment by kaklakariada** [comment]
Hi @elferherrera ,
thank you for your question!
If I understand you correctly you want to put a proxy between the Exasol database and the Go driver? The driver uses the [Exasol websocket API](https://github.com/exasol/websocket-api/), so it should be possible to create a websocket server that implements the same API and intercepts all requests. But you will need to parse the SQL statements which can get complex depending on your requirements.

Maybe an alternative solution could be [row-level-security](https://github.com/exasol/row-level-security-lua/#row-level-security-lua) which creates a virtual schema in Exasol that enforces row level security, i.e. users can only select rows for which they have permissions.

**Comment by elferherrera** [comment]
@kaklakariada thanks for the answer. The idea is to have a proxy between the user and the database. I would like to filter out suboptimal queries before the reach the DB. Also, I want to create a pool of connections outside the DB to reduce the load on exasol. 

I already have a simple concept with a TCP listener but what I'm looking is a way to encode and decode the messages sent from the user to exasol. I was wondering if the data definitions that you guys have in the repo could help me with that.

**Comment by kaklakariada** [comment]
@elferherrera OK, now I understand your usecase.
You can definitely use the code in this repo to parse the JSON messages sent between client and server, you can find details here: [Exasol websocket API](https://github.com/exasol/websocket-api/).

Another option for implementing this could be creating a REST service that accepts SQL queries from the client, filters suboptimal queries and forwards them to the Exasol database. Of course, this depends on your client application and if it is possible to modify it.

Please also keep in mind that not all Exasol clients use the WebSocket API. The Exasol drivers for JDBC and ODBC use a proprietary binary protocol, so this approach won't work there.

In this case the [SQL Preprocessor](https://docs.exasol.com/db/latest/database_concepts/sql_preprocessor.htm) might be an option. This allows you to pre-process SQL queries directly in the database and detect suboptimal queries. Then you could optimize the query automatically or reject it.

**Comment by elferherrera** [comment]
If I understand correctly, if I'm using pyexasol module the connection to exasol is done using websockets and JSON messages and Jdbc will use a binary protocol. Do you know is there is a way to get the specifications for the messages sent via jdbc?

**Comment by kaklakariada** [comment]
Yes, Pyexasol also uses the Websocket protocol. I am sorry, but it's not possible to get the spec for the binary protocol, because it is not an official interface and may change without warning.
I will ask my colleagues if there is another way to implement your requirements.

**Comment by elferherrera** [comment]
Thanks for the help. Btw, we wouldnt want to use the SQL preprocessor because the idea is the reduce the load on exasol db that's why we are thinking of this reverse proxy. We have identified several queries that consume resources and it doesnt make sense to have exasol even try to analyse them.

**Comment by kaklakariada** [comment]
Maybe the [resource manager](https://docs.exasol.com/db/latest/database_concepts/resource_manager.htm) and consumer groups could be a solution for you?

**Comment by elferherrera** [comment]
it seems that the sql preprocessor still registers a session in the database, right?
also, it doesnt seem that I can configure what queries I want killed. 

another example, say a user submits a query that takes too long to process. We have another process that identifies long running queries and kills them. I would like for the reverse proxy to not allow the same query to be run just after it was killed. It will consume resources that are going to be wasted again

**Comment by kaklakariada** [comment]
Yes, with the SQL preprocessor a new database session will be created when logging in to the database.
There is no direct way to kill a query but the `error("...")` function (see [example](https://docs.exasol.com/db/latest/database_concepts/sql_preprocessor.htm#Examples)) allows you to abort a query. You will need to parse the query and then decide if it should be killed or not.

If neither the resource manager nor the SQL preprocessor are an option and you also can't update the clients to avoid the expensive queries please create a [support ticket](https://www.exasol.com/support/secure/Dashboard.jspa). I am sure the experts can help you.

**Comment by kaklakariada** [comment]
I will closes this now. Do not hesitate to create a new issue if you have further questions.
