### ISSUE TITLE
Driver reports wrong version

### ISSUE THREAD

**Issue by CanburakTumer** [exasol/exasol-driver-go#76]
We found out in the `EXA_STATISTICS.EXA_DBA_AUDIT_SESSION` table driver logs itself as `exasol-driver-go v1.0.0` even though our user is currently using `v0.1.2` so I expect to see this version in the logs.

Exasol version: 7.0.18

**Comment by Nightapes** [comment]
@CanburakTumer thank you for reporting this issue. The version will be reported correctly with the next release.

**Comment by kaklakariada** [comment]
Thanks to @Nightapes for fixing the issue in #77!
The bugfix is contained the new release [v0.4.5](https://github.com/exasol/exasol-driver-go/releases/tag/v0.4.5).
