### ISSUE TITLE
FetchSize is bytes not kilobytes

### ISSUE THREAD

**Issue by stangelandcl** [exasol/exasol-driver-go#80]
Follow DSNConfigBuilder.FetchSize through and it sets FetchCommand.NumBytes in result_set.go without ever being multiplied by 1024.

**Comment by kaklakariada** [comment]
@stangelandcl 
We just released version [v0.4.6](https://github.com/exasol/exasol-driver-go/releases/tag/v0.4.6) with a bugfix for this.
